stages:
  - deploy

deploy_green:
  stage: deploy
  only:
    - web
  script:
    - sudo rm -rf /var/www/green/bitrix/modules/trusted.cryptoarmdocsbusiness/
    - sudo rm -rf /var/www/green/bitrix/modules/trusted.cryptoarmdocscrp/
    - sudo cp -R trusted.cryptoarmdocs/ /var/www/green/bitrix/modules/trusted.cryptoarmdocsbusiness/
    - sudo chown -R alr:www-data /var/www/green/bitrix/modules/trusted.cryptoarmdocsbusiness/
    - sudo find /var/www/green/bitrix/modules/trusted.cryptoarmdocsbusiness/ -type f -exec chmod 0664 {} \;
    - sudo find /var/www/green/bitrix/modules/trusted.cryptoarmdocsbusiness/ -type d -exec chmod 2775 {} \;
  when: manual

deploy_yellow:
  stage: deploy
  only:
    - web
  script:
    - sudo rm -rf /var/www/yellow/bitrix/modules/trusted.cryptoarmdocsbusiness/
    - sudo cp -R trusted.cryptoarmdocs/ /var/www/yellow/bitrix/modules/trusted.cryptoarmdocsbusiness/
    - sudo chown -R alr:www-data /var/www/yellow/bitrix/modules/trusted.cryptoarmdocsbusiness/
    - sudo find /var/www/yellow/bitrix/modules/trusted.cryptoarmdocsbusiness/ -type f -exec chmod 0664 {} \;
    - sudo find /var/www/yellow/bitrix/modules/trusted.cryptoarmdocsbusiness/ -type d -exec chmod 2775 {} \;

  when: manual

deploy_red:
  stage: deploy
  only:
    - web
  script:
    - sudo rm -rf /var/www/red/bitrix/modules/trusted.cryptoarmdocsbusiness/
    - sudo cp -R trusted.cryptoarmdocs/ /var/www/red/bitrix/modules/trusted.cryptoarmdocsbusiness/
    - sudo chown -R alr:www-data /var/www/red/bitrix/modules/trusted.cryptoarmdocsbusiness/
    - sudo find /var/www/red/bitrix/modules/trusted.cryptoarmdocsbusiness/ -type f -exec chmod 0664 {} \;
    - sudo find /var/www/red/bitrix/modules/trusted.cryptoarmdocsbusiness/ -type d -exec chmod 2775 {} \;
  when: manual
